### ISSUE TITLE
chaotic sqlite croaks on distinct queries

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/physionet-build#1743]
E.g.
```
>>> str(user.models.User.objects.all().distinct().query)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/user/ve-psetup/lib/python3.9/site-packages/django/db/models/sql/query.py", line 258, in __str__
    sql, params = self.sql_with_params()
  File "/home/user/ve-psetup/lib/python3.9/site-packages/django/db/models/sql/query.py", line 266, in sql_with_params
    return self.get_compiler(DEFAULT_DB_ALIAS).as_sql()
  File "/home/user/ve-psetup/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 499, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/home/user/ve-psetup/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 58, in pre_sql_setup
    extra_select = self.get_extra_select(order_by, self.select)
  File "/home/user/ve-psetup/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 404, in get_extra_select
    without_ordering = self.ordering_parts.search(sql)[1]
TypeError: 'NoneType' object is not subscriptable
```

Well...
```
    ordering_parts = _lazy_re_compile(
        r'^(.*)\s(?:ASC|DESC).*',
        re.MULTILINE | re.DOTALL,
    )
```
which is utterly nuts, but I guess it works as long as Django is generating all the SQL expressions itself.

I don't understand why `get_extra_select` is there in the first place, but there's probably a good reason for it.

Now, changing `RANDOM()` to `RANDOM() ASC` would make the queries run.  But (I think) that would prevent actually doing the desired DISTINCT-filtering, because `RANDOM()` would now be one of the queried columns.

So probably it would be wiser to disable randomization for DISTINCT queries.  Unless there is some other way we could inject an order while bypassing `get_extra_select`.

**Comment by bemoody** [comment]
Also note that passing fields to distinct() doesn't work because
```
DISTINCT ON fields is not supported by this database backend
```

**Comment by bemoody** [comment]
> Unless there is some other way we could inject an order while bypassing `get_extra_select`.

We could, of course, override `get_extra_select`, but I feel like that would make the tower of cards even more fragile for limited benefit.

**Comment by bemoody** [comment]
> which is utterly nuts

I mean, couldn't they at least have written this as `r'^(.*)\s(?:ASC|DESC)\s*$'`?  Come on.  Not to mention the MULTILINE bit.
