### ISSUE TITLE
The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES.

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#2030]
It looks like we're seeing a new error, presumably related to our recent update to the data upload form: https://github.com/MIT-LCP/physionet-build/pull/2028

```
The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES.

TooManyFilesSent at /projects/SLUG/files/
The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES.

Request Method: POST
Request URL: https://physionet.org/projects/SLUG/files/
Django Version: 4.1.9
Python Executable: /home/physionet/python-env/physionet/bin/uwsgi
Python Version: 3.9.2
Python Path: ['.', '', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/physionet/python-env/physionet/lib/python3.9/site-packages']
Server time: Thu, 22 Jun 2023 15:19:31 -0400
Installed Applications:
['dal',
'dal_select2',
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.sites',
'django.contrib.redirects',
'ckeditor',
'background_task',
'rest_framework',
'user',
'project',
'console',
'export',
'notification',
'search',
'physionet',
'django_sass',
'events',
'lightwave']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
'physionet.middleware.maintenance.SystemMaintenanceMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'django.contrib.redirects.middleware.RedirectFallbackMiddleware']


Traceback (most recent call last):
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
   response = get_response(request)
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/base.py", line 185, in _get_response
   response = middleware_method(
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/middleware/csrf.py", line 471, in process_view
   self._check_token(request)
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/middleware/csrf.py", line 374, in _check_token
   request_csrf_token = request.POST.get("csrfmiddlewaretoken", "")
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 100, in _get_post
   self._load_post_and_files()
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/http/request.py", line 373, in _load_post_and_files
   self._post, self._files = self.parse_file_upload(self.META, data)
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/http/request.py", line 323, in parse_file_upload
   return parser.parse()
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/http/multipartparser.py", line 123, in parse
   return self._parse()
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/http/multipartparser.py", line 260, in _parse
   raise TooManyFilesSent(

Exception Type: TooManyFilesSent at /projects/SLUG/files/
Exception Value: The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES.
Raised during: project.views.view_wrapper
Request information:
USER: USERNAME
```

**Comment by tompollard** [comment]
Fixed, see: https://github.com/MIT-LCP/physionet-build/issues/2035
