### ISSUE TITLE
The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#2035]
The following error is being raised fairly regularly by users attempting to upload files. 

See https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-DATA_UPLOAD_MAX_NUMBER_FILES for documentation on DATA_UPLOAD_MAX_NUMBER_FILES. 

Relates to https://github.com/MIT-LCP/physionet-build/pull/2028. It looks like DATA_UPLOAD_MAX_NUMBER_FILES is currently set to 100 [UPDATE: the default is 100, so I assume it isn't being actively set).

```
The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES.

TooManyFilesSent at /projects/SLUG/files/
The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES.

Request Method: POST
Request URL: https://physionet.org/projects/SLUG/files/
Django Version: 4.1.9
Python Executable: /home/physionet/python-env/physionet/bin/uwsgi
Python Version: 3.9.2
Python Path: ['.', '', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/physionet/python-env/physionet/lib/python3.9/site-packages']
Installed Applications:
['dal',
'dal_select2',
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.sites',
'django.contrib.redirects',
'ckeditor',
'background_task',
'rest_framework',
'oauth2_provider',
'corsheaders',
'user',
'project',
'console',
'export',
'notification',
'search',
'physionet',
'django_sass',
'events',
'oauth',
'lightwave']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
'physionet.middleware.maintenance.SystemMaintenanceMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'corsheaders.middleware.CorsMiddleware',
'oauth2_provider.middleware.OAuth2TokenMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'django.contrib.redirects.middleware.RedirectFallbackMiddleware']


Traceback (most recent call last):
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
   response = get_response(request)
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/base.py", line 185, in _get_response
   response = middleware_method(
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/middleware/csrf.py", line 471, in process_view
   self._check_token(request)
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/middleware/csrf.py", line 374, in _check_token
   request_csrf_token = request.POST.get("csrfmiddlewaretoken", "")
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 100, in _get_post
   self._load_post_and_files()
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/http/request.py", line 373, in _load_post_and_files
   self._post, self._files = self.parse_file_upload(self.META, data)
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/http/request.py", line 323, in parse_file_upload
   return parser.parse()
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/http/multipartparser.py", line 123, in parse
   return self._parse()
 File "/physionet/python-env/physionet/lib/python3.9/site-packages/django/http/multipartparser.py", line 260, in _parse
   raise TooManyFilesSent(

Exception Type: TooManyFilesSent at /projects/SLUG/files/
Exception Value: The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES.
Raised during: project.views.view_wrapper
Request information:
USER: USERNAME

GET: No GET data

POST: No POST data

FILES: No FILES data
5f719w1cfo2jx1gsvzq9ynd'
HTTP_DNT = '1'
HTTP_HOST = '[physionet.org](http://physionet.org/)'
HTTP_ORIGIN = 'https://physionet.org/'
HTTP_REFERER = 'https://physionet.org/projects/8OV31CqkoNSROwdVeefX/files/'
HTTP_SEC_FETCH_DEST = 'document'
HTTP_SEC_FETCH_MODE = 'navigate'
HTTP_SEC_FETCH_SITE = 'same-origin'
HTTP_SEC_FETCH_USER = '?1'
HTTP_TE = 'trailers'
HTTP_UPGRADE_INSECURE_REQUESTS = '1'
HTTP_USER_AGENT = 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0'
PATH_INFO = '/projects/8OV31CqkoNSROwdVeefX/files/'
QUERY_STRING = ''
REMOTE_ADDR = '212.235.188.5'
REMOTE_PORT = '39995'
REQUEST_METHOD = 'POST'
REQUEST_SCHEME = 'https'
REQUEST_URI = '/projects/8OV31CqkoNSROwdVeefX/files/'
SCRIPT_NAME = ''
SERVER_NAME = '[physionet.org](http://physionet.org/)'
SERVER_PORT = '443'
SERVER_PROTOCOL = 'HTTP/2.0'
uwsgi.node = b'physionet-live'
uwsgi.version = b'2.0.21'
wsgi.errors = <_io.TextIOWrapper name=2 mode='w' encoding='UTF-8'>
wsgi.file_wrapper = <built-in function uwsgi_sendfile>
wsgi.input = <uwsgi._Input object at 0x7f01b6aad5f0>
wsgi.multiprocess = True
wsgi.multithread = False
wsgi.run_once = False
wsgi.url_scheme = 'https'
wsgi.version = '(1, 0)'

Settings:

DATA_UPLOAD_MAX_NUMBER_FILES = 100
```

**Comment by tompollard** [comment]
Addressed in https://github.com/MIT-LCP/physionet-build/pull/2036
