### ISSUE TITLE
Error loading news fixtures on staging: psycopg2.DataError: value too long for type character varying(40)

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#449]
Attempting to load the fixtures added in: https://github.com/MIT-LCP/physionet-build/pull/447 raises a `value too long for type character varying(40)` error on the staging server. Loading is fine locally, so this appears to be sqllite vs postgres issue:

```
python manage.py loaddata news-1999-2011.json
```

```
Traceback (most recent call last):
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(40)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 113, in loaddata
    self.load_label(fixture_label)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 177, in load_label
    obj.save(using=self.using)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/core/serializers/base.py", line 219, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/physionet/python-env/physionet/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: Problem installing fixture '/physionet/physionet-build/physionet-django/notification/fixtures/news-1999-2011.json': Could not load notification.News(pk=None): value too long for type character varying(40)
```

**Comment by bemoody** [comment]
Dang.  I tested it locally, but I guess sqlite doesn't enforce the size limit.

**Comment by tompollard** [comment]
Fixtures successfully loaded :) 

News at: https://alpha.physionet.org/news/

Feed at: https://alpha.physionet.org/feed.xml
